<?php

namespace AppBundle\Repository;

/**
 * FilmFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmFormatRepository extends \Doctrine\ORM\EntityRepository
{
}
