<?php

namespace AppBundle\Repository;

/**
 * MovieTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
