<?php

namespace AppBundle\Repository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPriceFor($name)
    {
        $price = $this->findOneBy(array('name' => $name));

        if (empty($price)) {
            return 0.00;
        }

        return $price->getAmount();
    }
}
