<?php

namespace AppBundle\Repository;

/**
 * ScreenSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenSizeRepository extends \Doctrine\ORM\EntityRepository
{
}
