<?php

namespace AppBundle\Repository;

/**
 * SeatTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
