<?php

namespace AppBundle\Repository;

/**
 * SoundFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoundFormatRepository extends \Doctrine\ORM\EntityRepository
{
}
