<?php

namespace AppBundle\Repository;

/**
 * TheaterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheaterTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
