<?php

namespace AppBundle\Repository;

/**
 * TheaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TheaterRepository extends \Doctrine\ORM\EntityRepository
{
}
